name: Python application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependecies
      run: |
        python -m venv venv
        source venv/bin/activate
        export PYTHONPATH="${{ github.workspace }}"
        pip install --upgrade pip
        pip install pytest
        pip install pytest pytest-cov

    - name: Run tests
      run: | 
        source venv/bin/activate
        export PYTHONPATH="${{ github.workspace }}"
        pytest
        pytest --cov=. --cov-fail-under=100
